# Add 'label1' to any changes within 'example' folder or any subfolders
area/docs:
  - docs/**/*
  - ./*.md

area/testing:
  - tests/**/*

area/setup:
  - setup.py
  - extra-requirements.txt
  - requirements.txt
  - MANIFEST.in

area/core:
  - docarray/**/*

area/entrypoint:
  - docarray/__init__.py

area/housekeeping:
  - .github/**/*
  - ./.gitignore
  - ./*.yaml
  - ./*.yml

area/cicd:
  - .github/workflows/**/*

area/docker:
  - Dockerfiles/**/*
  - ./.dockerignore

area/typing:
  - script/**/*

component/array:
  - docarray/array/**/*

component/document:
  - docarray/document/**/*

component/proto:
  - docarray/proto/**/*

