name: 🐛 DocArray Bug (>=0.30.0 )
description: Report a bug or unexpected behavior in DocArray (v2) above (0.30.0)
labels: [bug V2, unconfirmed]

body:
  - type: markdown
    attributes:
      value:  Thank you for contributing to DocArray! 🙌

  - type: markdown
    attributes:
      value:  "credits: This issue template is heavily inspired by [pydantic template](https://github.com/pydantic/pydantic/tree/main/.github/ISSUE_TEMPLATE)"


  - type: checkboxes
    id: checks
    attributes:
      label: Initial Checks
      description: |
        Just a few checks to make sure you need to create a bug report.
      options:
        - label: I have read and followed [the docs](https://docs.docarray.org/) and still think this is a bug
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please explain what you're seeing and what you would expect to see.

        Please provide as much detail as possible to make understanding and solving your problem as quick as possible. 🙏
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: >
        If applicable, please add a self-contained,
        [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example)
        demonstrating the bug.

      placeholder: |
        import docarray

        ...
      render: Python

  - type: textarea
    id: version
    attributes:
      label: Python, Pydantic & OS Version
      description: |
        Which version of Python & Pydantic are you using, and which Operating System?

        Please run the following command and copy the output below:

        ```bash
        python -c "import docarray; print(docarray.__version__);"
        ```

      render: Text
    validations:
      required: true

  - type: checkboxes
    id: affected-components
    attributes:
      label: Affected Components
      description: Which of the following parts of pydantic does this feature affect?
      # keep this lis in sync with bug.yml
      options:
        - label: '[Vector Database / Index](https://docs.docarray.org/user_guide/storing/docindex/)'
        - label: '[Representing](https://docs.docarray.org/user_guide/representing/first_step)'
        - label: '[Sending](https://docs.docarray.org/user_guide/sending/first_step/)'
        - label: '[storing](https://docs.docarray.org/user_guide/storing/first_step/)'
        - label: '[multi modal data type](https://docs.docarray.org/data_types/first_steps/)'

