name: 🚀 DocArray Feature request
description: |
  Suggest a new feature for DocArray

labels: [feature request]

body:
  - type: markdown
    attributes:
      value: Thank you for contributing to docarray! ✊

  - type: markdown
    attributes:
      value:  "credits: This issue template is heavily inspired by [pydantic template](https://github.com/pydantic/pydantic/tree/main/.github/ISSUE_TEMPLATE)"

  - type: checkboxes
    id: searched
    attributes:
      label: Initial Checks
      description: |
        Just a few checks to make sure you need to create a feature request.

      options:
        - label: I have searched Google & GitHub for similar requests and couldn't find anything
          required: true
        - label: I have read and followed [the docs](https://docs.docarray.org) and still think this feature is missing
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please give as much detail as possible about the feature you would like to suggest. 🙏

        You might like to add:
        * A demo of how code might look when using the feature
        * Your use case(s) for the feature
        * Why the feature should be added to DocArray (as opposed to another library or just implemented in your code)
    validations:
      required: true

  - type: checkboxes
    id: affected-components
    attributes:
      label: Affected Components
      description: Which of the following parts of DocArray does this feature affect?
      # keep this lis in sync with bug.yml
      options:
        - label: '[Vector Database / Index](https://docs.docarray.org/user_guide/storing/docindex/)'
        - label: '[Representing](https://docs.docarray.org/user_guide/representing/first_step)'
        - label: '[Sending](https://docs.docarray.org/user_guide/sending/first_step/)'
        - label: '[storing](https://docs.docarray.org/user_guide/storing/first_step/)'
        - label: '[multi modal data type](https://docs.docarray.org/data_types/first_steps/)'
