name: Uncaped

on:
  schedule:
    - cron:  '0 0,1 * * *'  # Run at midnight, 1 AM UTC

jobs:
  docarray-test-uncaped:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        test-path: [tests/integrations, tests/units, tests/documentation]
    steps:
      - uses: actions/checkout@v2.5.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Prepare environment
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          rm poetry.lock
          poetry install --all-extras
          poetry run pip install elasticsearch==8.6.2
          sudo apt-get update
          sudo apt-get install --no-install-recommends ffmpeg

      - name: Test
        id: test
        run: |
          poetry run pytest -m "not (tensorflow or benchmark or index)" ${{ matrix.test-path }} --ignore=tests/integrations/store/test_jac.py
        timeout-minutes: 30
        env:
          JINA_AUTH_TOKEN: "${{ secrets.JINA_AUTH_TOKEN }}"
